SELECT 
*  
FROM "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO4"
WHERE "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO4"."U_FIGU_SG4_IN" = 'N';


-- **************************************************

SELECT
 --T0."U_FIGU_LINK_SG3",
 T1."Name",
 T0."Code",
 T0."Name",
 T0."U_SYP_PREFIJO",
 T0."U_FIGU_SG4_IN"
 
FROM "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO4" T0
INNER JOIN "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO3" T1 ON T0."U_FIGU_LINK_SG3" = T1."Code"
WHERE CAST(T0."U_FIGU_SG4_IN" AS VARCHAR)  = 'N';