SELECT * FROM "_SYS_BIC"."sap.b1hepmprod/EPM_MOV_LOTES" WHERE "ItmsGrpNam" = 'PROD. TERMINADO EPM' LIMIT 100;

SELECT * FROM "_SYS_BIC"."sap.b1hepmprod/EPM_MOV_LOTES" WHERE "ItmsGrpNam" = 'SEMIELABORADO EPM' LIMIT 100;
  