SELECT 
T0."ItemCode", T0."ItemName",
T3."Name" as "FAMILIA", T4."Name" AS "SUBFAMILIA",
T0."U_SYP_PADRE_BOB"

FROM OITM T0
LEFT JOIN "SBO_FIGURETTI_PRO"."@SYP_GRUPO" A0 ON T0."U_SYP_GRUPO" = A0."Code"
LEFT JOIN "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO1" T1 ON T0."U_SYP_SUBGRUPO1" = T1."Code"
LEFT JOIN "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO2" T2 ON T0."U_SYP_SUBGRUPO2" = T2."Code"
LEFT JOIN "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO3" T3 ON T0."U_SYP_SUBGRUPO3" = T3."Code"
LEFT JOIN "SBO_FIGURETTI_PRO"."@SYP_SUBGRUPO4" T4 ON T0."U_SYP_SUBGRUPO4" = T4."Code" 
WHERE 
   T0."validFor" = 'Y'
GROUP BY T0."ItemCode", T0."ItemName",
T3."Name", T4."Name", T0."U_SYP_PADRE_BOB"