BEGIN

DECLARE GRUPOB  NVARCHAR(10);
DECLARE SUBGRUPO2  NVARCHAR(15);
DECLARE SUBGRUPO3  NVARCHAR(15);
DECLARE SUBGRUPO4  NVARCHAR(15);

DECLARE NEWSEC  NVARCHAR(15);
DECLARE SEC INTEGER;
DECLARE ITEMCODE  NVARCHAR(15);



Select $[OITM."U_SYP_GRUPO"] into GRUPOB  fROM dummy;
Select $[OITM."U_SYP_SUBGRUPO2"] into SUBGRUPO2  fROM dummy;
Select $[OITM."U_SYP_SUBGRUPO3"] into SUBGRUPO3  fROM dummy;
Select $[OITM."U_SYP_SUBGRUPO4"] into SUBGRUPO4  fROM dummy;

Select ifnull($[OITM."ItemCode".0],'') into ITEMCODE  fROM dummy;

if (:ITEMCODE='' AND (:GRUPOB='01D' OR :GRUPOB='03F' OR :GRUPOB='04D' OR :GRUPOB='05D' )) then 

	SELECT MAX(CAST(SUBSTRING(T0."ItemCode", 10,4) AS INTEGER)) INTO SEC FROM OITM T0 WHERE T0."U_SYP_GRUPO" = :GRUPOB AND T0."U_SYP_SUBGRUPO2" = :SUBGRUPO2 AND "U_SYP_SUBGRUPO4" = :SUBGRUPO4 ;
		  
	SELECT (IFNULL(:SEC, 0) + 1 ) INTO SEC fROM DUMMY;

	SELECT LPAD ( (SELECT :SEC fROm dUMMY ),4,'0') iNTO NEWSEC fROM dUMMY;

             SELECT CONCAT(:GRUPOB ,CONCAT(:SUBGRUPO2 , CONCAT(:SUBGRUPO4,:NEWSEC ))) fROM dUMMY;

	else
	if (:ITEMCODE='' AND (:GRUPOB='01B' OR :GRUPOB='02D' OR :GRUPOB='02B' OR :GRUPOB='09B' OR :GRUPOB='07D' OR :GRUPOB='00F' OR :GRUPOB='99A')) then 

				SELECT MAX(CAST(SUBSTRING(T0."ItemCode", 10,4) AS INTEGER)) INTO SEC FROM OITM T0 WHERE T0."U_SYP_GRUPO" = :GRUPOB AND T0."U_SYP_SUBGRUPO3" = :SUBGRUPO3 AND "U_SYP_SUBGRUPO4" = :SUBGRUPO4 ;
		  
				SELECT (IFNULL(:SEC, 0) + 1 ) INTO SEC fROM DUMMY;

				SELECT LPAD ( (SELECT :SEC fROm dUMMY ),4,'0') iNTO NEWSEC fROM dUMMY;

				SELECT CONCAT(:GRUPOB ,CONCAT(:SUBGRUPO3 , CONCAT(:SUBGRUPO4,:NEWSEC ))) fROM dUMMY;

		else
		if (:ITEMCODE !='' ) then

			Select :ITEMCODE from dummy;

		end if;

	end if;

end if;

END;