
SELECT T0."ItemCode", T0."ItemName", T0."U_SYP_CODE_SKU", T0."U_SYP_MARCA" FROM OITM T0 LIMIT 10

/* LISTA LA QUE NO ESTAN VACIAS en sku y marca*/
SELECT T0."ItemCode", T0."ItemName", T0."U_SYP_CODE_SKU", T0."U_SYP_MARCA"
FROM OITM T0
WHERE T0."U_SYP_CODE_SKU" IS NOT NULL AND T0."U_SYP_MARCA" IS NOT NULL;

/* lista las que si estan vacias en sku y marca */
SELECT T0."ItemCode", T0."ItemName", T0."U_SYP_CODE_SKU", T0."U_SYP_MARCA"
FROM OITM T0
WHERE (T0."U_SYP_CODE_SKU" IS NULL OR T0."U_SYP_CODE_SKU" = '') 
AND (T0."U_SYP_MARCA" IS NULL OR T0."U_SYP_MARCA" = '');
