
/* ejemplos */
EXPORT "B1H_EPM_PROD"."*" AS BINARY INTO '/usr/sap/NDB/HDB00/backup/data/B1H_EPM_PROD_20250130' 
WITH REPLACE THREADS 10;

IMPORT "B1H_EPM_PROD"."*" AS BINARY FROM '/usr/sap/NDB/HDB00/backup/data/B1H_EPM_PROD_20250130' 
WITH REPLACE THREADS 10 RENAME SCHEMA "B1H_EPM_PROD" TO "B1H_EPM_PROD_202501"


/* ejemplo */

EXPORT "SBODEMOUS"."*" AS BINARY INTO '/usr/sap/HDB/HDB00/work/backups/SBODEMOUS' 
WITH REPLACE THREADS 8

IMPORT "SBODEMOUS"."*" AS BINARY FROM '/usr/sap/HDB/HDB00/work/backups/SBODEMOUS' 
WITH REPLACE THREADS 8 RENAME SCHEMA "SBODEMOUS" TO "SBODEMOUS_COPY", "SBOCOMMON" TO "SBOCOMMON_TEMP"


/* error
     java.sql.SQLWarning: general warning: Type mismatch for table variable "TMP" : Target type "NVARCHAR(1)" of attribute "IMP RENTA SOC" not same as assigned type "NVARCHAR(5000)" line 9 col 1 (at por 205)

 */

SELECT TABLE_NAME 
FROM TABLE_COLUMNS 
WHERE SCHEMA_NAME = 'SBODEMOUS' 
AND COLUMN_NAME = 'IMP RENTA SOC';